name: Full Platform Build
on: workflow_dispatch

jobs:
  build:
    name: Build for ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - platform: Windows
            os: windows-latest
            build_cmd: flutter build windows --release
            artifact_path: simple_live_app/build/windows/runner/Release/
          - platform: Android
            os: ubuntu-latest
            build_cmd: flutter build apk --release --target-platform android-arm64
            artifact_path: simple_live_app/build/app/outputs/flutter-apk/*.apk
          - platform: iOS
            os: macos-latest
            build_cmd: flutter build ios --release --no-codesign # 无证书编译
            artifact_path: simple_live_app/build/ios/iphoneos/*.app

    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true
      - name: Get Dependencies
        run: |
          cd simple_live_app
          flutter pub get
      - name: Build Platform
        run: |
          cd simple_live_app
          ${{ matrix.build_cmd }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimpleLive-${{ matrix.platform }}
          path: ${{ matrix.artifact_path }}
